import { useEffect, useState } from "react";
import { api } from "../lib/api";

type Cap={enabled:boolean;allows_self:boolean;rafael_signer:boolean};
type Rx={id:number;patient_name:string|null;body:string;mode:"propria"|"rafael";status:string;originator_name:string|null;review_note:string|null;signed:boolean;pdf_available:boolean;awaiting_external_signature:boolean};
type Pv={codigo:string;nome:string;nivel:string;disponivel:boolean};
const L:Record<string,string>={pronta_assinatura:"Pronta para assinatura",pendente_assinatura:"Aguardando Dr. Rafael",aprovada:"Aprovada",devolvida:"Devolvida",recusada:"Recusada",aguardando_assinatura_externa:"Aguardando PDF assinado",emitida_manual:"Emitida para assinatura manual",assinado:"Assinada"};

export default function PrescricaoLivreEspecial(){
 const[c,setC]=useState<Cap>();const[m,setM]=useState<Rx[]>([]);const[f,setF]=useState<Rx[]>([]);const[p,setP]=useState<Pv[]>([]);const[n,setN]=useState("");const[t,setT]=useState("");const[modo,setModo]=useState<"propria"|"rafael">("rafael");const[ed,setEd]=useState<number>();const[e,setE]=useState("");
 async function load(){const x=await api.get<Cap>("/prescricao-especial/capacidades");setC(x);if(x.enabled)setM(await api.get<Rx[]>("/prescricao-especial/minhas"));if(x.rafael_signer)setF(await api.get<Rx[]>("/prescricao-especial/pendentes"));}
 useEffect(()=>{load().catch(()=>{});api.get<Pv[]>("/assinatura/provedores").then(setP).catch(()=>{});},[]);useEffect(()=>{if(c&&!c.allows_self)setModo("rafael")},[c]);
 if(!c||(!c.enabled&&!c.rafael_signer))return null;
 const err=(x:unknown)=>setE(x instanceof Error?x.message:"Falha na operação.");
 const save=async()=>{try{const x={patient_name:n.trim(),body:t.trim()};ed?await api.put(`/prescricao-especial/${ed}`,x):await api.post("/prescricao-especial",{...x,mode:modo});setN("");setT("");setEd(undefined);await load()}catch(x){err(x)}};
 const decide=async(r:Rx,a:string)=>{const note=a==="aprovar"?null:prompt(a==="devolver"?"Orientação para correção:":"Motivo da recusa:");if(a!=="aprovar"&&!note)return;try{await api.post(`/prescricao-especial/${r.id}/decisao`,{action:a,note});await load()}catch(x){err(x)}};
 const emit=async(r:Rx)=>{const q=p.filter(x=>x.disponivel&&(r.mode!=="rafael"||(x.nivel==="qualificada"&&x.codigo!=="MANUAL")));const def=q.find(x=>x.codigo==="A1_ARQUIVO")?.codigo||q[0]?.codigo;if(!def)return setE("Nenhuma assinatura disponível.");const metodo=prompt(`Método de assinatura (${q.map(x=>x.codigo).join(", ")}):`,def);if(!metodo)return;try{const b=await api.blobPost(`/prescricao-especial/${r.id}/emitir`,{metodo,endereco:"profissional"});const u=URL.createObjectURL(b);window.open(u,"_blank","noopener,noreferrer");await load()}catch(x){err(x)}};
 const upload=async(r:Rx,z?:File)=>{if(z)try{await api.upload(`/prescricao-especial/${r.id}/assinatura-externa`,"arquivo",z);await load()}catch(x){err(x)}};
 const pdf=async(r:Rx)=>{try{const b=await api.blob(`/prescricao-especial/${r.id}/pdf`),u=URL.createObjectURL(b);window.open(u,"_blank","noopener,noreferrer")}catch(x){err(x)}};
 const mail=async(r:Rx)=>{const to=prompt("E-mail do destinatário:");if(to)try{const x=await api.post<{enviado:boolean;link:string|null}>(`/prescricao-especial/${r.id}/enviar-email`,{email:to});if(!x.enviado&&x.link)prompt("Copie o link seguro:",x.link)}catch(x){err(x)}};
 const card=(r:Rx,dr=false)=><div className="cartao" key={r.id} style={{marginTop:6}}><strong>{r.patient_name}{dr&&` · ${r.originator_name??"usuário"}`}</strong> · {L[r.status]||r.status}<p style={{whiteSpace:"pre-wrap"}}>{r.body}</p>{r.review_note&&<p>{r.review_note}</p>}{dr&&r.status==="pendente_assinatura"&&<p><button className="botao" onClick={()=>decide(r,"aprovar")}>Aprovar</button> <button className="botao botao--secundario" onClick={()=>decide(r,"devolver")}>Devolver</button> <button className="botao botao--secundario" onClick={()=>decide(r,"recusar")}>Recusar</button></p>}{(r.status==="pronta_assinatura"||(dr&&r.status==="aprovada"))&&<button className="botao" onClick={()=>emit(r)}>Emitir/assinar</button>}{r.status==="devolvida"&&!dr&&<button className="botao" onClick={()=>{setEd(r.id);setN(r.patient_name||"");setT(r.body)}}>Corrigir</button>}{r.awaiting_external_signature&&<label className="botao">Enviar PDF assinado<input hidden type="file" accept="application/pdf" onChange={x=>upload(r,x.target.files?.[0])}/></label>}{r.pdf_available&&!dr&&<p><button className="botao" onClick={()=>pdf(r)}>Abrir/Imprimir/Download</button> <button className="botao botao--secundario" onClick={()=>mail(r)}>E-mail</button></p>}</div>;
 return <div className="cartao" style={{marginBottom:12}}><p className="eyebrow">Prescrição livre</p>{e&&<p role="alert">{e}</p>}{c.enabled&&<><input placeholder="Paciente" value={n} onChange={x=>setN(x.target.value)}/><textarea rows={7} placeholder="Digite livremente a prescrição, posologia e orientações…" value={t} onChange={x=>setT(x.target.value)}/>{!ed&&c.allows_self&&<select value={modo} onChange={x=>setModo(x.target.value as "propria"|"rafael")}><option value="propria">Emitir com minhas credenciais</option><option value="rafael">Enviar ao Dr. Rafael</option></select>}{!c.allows_self&&<p>Emissão somente pelo Dr. Rafael.</p>}<button className="botao" disabled={!n.trim()||!t.trim()} onClick={save}>{ed?"Enviar correção":modo==="rafael"?"Enviar ao Dr. Rafael":"Criar para emissão"}</button>{m.map(x=>card(x))}</>}{c.rafael_signer&&f.map(x=>card(x,true))}</div>;
}