import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, ApiError } from "../lib/api";
import { useAuth } from "../lib/auth";
import AssinaturaExternaITI from "../components/AssinaturaExternaITI";
import CalculadorasPreOperatoriasAvancadas, { type AvancadosState } from "../components/CalculadorasPreOperatoriasAvancadas";

const METODOS_MANUAL_EXTERNO = new Set(["GOVBR", "VIDAAS", "BIRDID", "SAFEID", "NEOID", "REMOTEID"]);
type Provedor = { codigo: string; nome: string; nivel: string; familia: string; disponivel: boolean; motivo: string | null };

type RcriEntrada = { cirurgia_alto_risco: boolean; cardiopatia_isquemica: boolean; insuficiencia_cardiaca_congestiva: boolean; doenca_cerebrovascular: boolean; diabetes_em_uso_de_insulina: boolean; creatinina_maior_2: boolean };
const RCRI_INICIAL: RcriEntrada = { cirurgia_alto_risco: false, cardiopatia_isquemica: false, insuficiencia_cardiaca_congestiva: false, doenca_cerebrovascular: false, diabetes_em_uso_de_insulina: false, creatinina_maior_2: false };
const RCRI_LABELS: Record<keyof RcriEntrada, string> = { cirurgia_alto_risco: "Cirurgia de alto risco", cardiopatia_isquemica: "Cardiopatia isquêmica", insuficiencia_cardiaca_congestiva: "Insuficiência cardíaca congestiva", doenca_cerebrovascular: "Doença cerebrovascular", diabetes_em_uso_de_insulina: "Diabetes em uso de insulina", creatinina_maior_2: "Creatinina sérica pré-operatória >2,0 mg/dL" };

type GuptaEntrada = { idade: string; status_funcional: string; asa: string; creatinina_maior_1_5: boolean; tipo_procedimento: string };
const GUPTA_PROCEDIMENTOS: [string, string][] = [["hernia","Hérnia"],["anorretal","Anorretal"],["aortica","Aórtica"],["bariatrica","Bariátrica"],["encefalica","Encefálica"],["mama","Mama"],["cardiaca","Cardíaca"],["orl","Otorrinolaringológica"],["foregut_hpb","GI alto/hepatopancreatobiliar"],["vesicula_apendice_adrenal_baco","Vesícula/apêndice/adrenal/baço"],["intestinal","Intestinal"],["pescoco","Pescoço"],["obstetrica_ginecologica","Obstétrica/ginecológica"],["ortopedica","Ortopédica"],["abdome_outro","Abdominal, outra"],["vascular_periferica","Vascular periférica"],["pele","Pele/tecido subcutâneo"],["coluna","Coluna"],["toracica","Torácica não cardíaca"],["veias","Veias"],["urologia","Urológica"]];

type DasiEntrada = { autocuidado: boolean; caminhar_casa: boolean; caminhar_quarteiroes: boolean; escada_ladeira: boolean; correr_curto: boolean; trabalho_domestico_leve: boolean; trabalho_domestico_moderado: boolean; trabalho_domestico_pesado: boolean; quintal_jardim: boolean; relacoes_sexuais: boolean; recreacao_moderada: boolean; esporte_extenuante: boolean };
const DASI_INICIAL: DasiEntrada = { autocuidado:false,caminhar_casa:false,caminhar_quarteiroes:false,escada_ladeira:false,correr_curto:false,trabalho_domestico_leve:false,trabalho_domestico_moderado:false,trabalho_domestico_pesado:false,quintal_jardim:false,relacoes_sexuais:false,recreacao_moderada:false,esporte_extenuante:false };
const DASI_LABELS: Record<keyof DasiEntrada,string> = { autocuidado:"Autocuidado (+2,75)", caminhar_casa:"Caminha dentro de casa (+1,75)", caminhar_quarteiroes:"Caminha 1–2 quarteirões (+2,75)", escada_ladeira:"Sobe escadas/ladeira (+5,5)", correr_curto:"Corre curta distância (+8,0)", trabalho_domestico_leve:"Trabalho doméstico leve (+2,7)", trabalho_domestico_moderado:"Trabalho doméstico moderado (+3,5)", trabalho_domestico_pesado:"Trabalho doméstico pesado (+8,0)", quintal_jardim:"Quintal/jardim (+4,5)", relacoes_sexuais:"Relações sexuais (+5,25)", recreacao_moderada:"Recreação moderada (+6,0)", esporte_extenuante:"Esporte extenuante (+7,5)" };

type AubEntrada = { historia_doenca_cardiaca:boolean; sintomas_cardiacos:boolean; idade_maior_igual_75:boolean; hemoglobina_menor_12:boolean; cirurgia_vascular:boolean; cirurgia_emergencia:boolean };
const AUB_INICIAL:AubEntrada={historia_doenca_cardiaca:false,sintomas_cardiacos:false,idade_maior_igual_75:false,hemoglobina_menor_12:false,cirurgia_vascular:false,cirurgia_emergencia:false};
const AUB_LABELS:Record<Exclude<keyof AubEntrada,"idade_maior_igual_75">,string>={historia_doenca_cardiaca:"História de doença cardíaca",sintomas_cardiacos:"Angina ou dispneia",hemoglobina_menor_12:"Hemoglobina <12 g/dL",cirurgia_vascular:"Cirurgia vascular",cirurgia_emergencia:"Cirurgia de emergência"};

type VsgEntrada={idade:string;doenca_arterial_coronariana:boolean;insuficiencia_cardiaca:boolean;dpoc:boolean;creatinina_maior_1_8:boolean;tabagismo:boolean;diabetes_insulina:boolean;betabloqueador_cronico:boolean;revascularizacao_coronaria_previa:boolean};
const VSG_INICIAL:VsgEntrada={idade:"",doenca_arterial_coronariana:false,insuficiencia_cardiaca:false,dpoc:false,creatinina_maior_1_8:false,tabagismo:false,diabetes_insulina:false,betabloqueador_cronico:false,revascularizacao_coronaria_previa:false};
const VSG_LABELS:Record<Exclude<keyof VsgEntrada,"idade">,string>={doenca_arterial_coronariana:"Doença arterial coronariana (+2)",insuficiencia_cardiaca:"Insuficiência cardíaca (+2)",dpoc:"DPOC (+2)",creatinina_maior_1_8:"Creatinina >1,8 mg/dL (+2)",tabagismo:"Tabagismo (+1)",diabetes_insulina:"Diabetes em uso de insulina (+1)",betabloqueador_cronico:"Betabloqueador crônico (+1)",revascularizacao_coronaria_previa:"Revascularização coronária prévia (−1)"};

function baixarBlob(blob:Blob,nome:string){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=nome;a.click();URL.revokeObjectURL(url)}

export default function AvaliacaoPreOperatoria(){
 const {usuario}=useAuth(); const [provedores,setProvedores]=useState<Provedor[]|null>(null);
 const [patientName,setPatientName]=useState(""); const [idade,setIdade]=useState(""); const [procedimento,setProcedimento]=useState(""); const [indicacao,setIndicacao]=useState(""); const [capacidadeFuncional,setCapacidadeFuncional]=useState(""); const [conduta,setConduta]=useState(""); const [endereco,setEndereco]=useState<""|"residencial"|"profissional">("");
 const [usarRcri,setUsarRcri]=useState(true); const [rcri,setRcri]=useState<RcriEntrada>(RCRI_INICIAL); const [resultadoRcri,setResultadoRcri]=useState<any>(null); const [interpretacaoRcri,setInterpretacaoRcri]=useState("");
 const [usarGupta,setUsarGupta]=useState(true); const [gupta,setGupta]=useState<GuptaEntrada>({idade:"",status_funcional:"independente",asa:"2",creatinina_maior_1_5:false,tipo_procedimento:"hernia"}); const [resultadoGupta,setResultadoGupta]=useState<any>(null); const [interpretacaoGupta,setInterpretacaoGupta]=useState("");
 const [usarDasi,setUsarDasi]=useState(true); const [dasi,setDasi]=useState<DasiEntrada>(DASI_INICIAL); const [resultadoDasi,setResultadoDasi]=useState<any>(null); const [interpretacaoDasi,setInterpretacaoDasi]=useState("");
 const [usarAub,setUsarAub]=useState(false); const [aub,setAub]=useState<AubEntrada>(AUB_INICIAL); const [resultadoAub,setResultadoAub]=useState<any>(null); const [interpretacaoAub,setInterpretacaoAub]=useState("");
 const [usarVsg,setUsarVsg]=useState(false); const [vsg,setVsg]=useState<VsgEntrada>(VSG_INICIAL); const [resultadoVsg,setResultadoVsg]=useState<any>(null); const [interpretacaoVsg,setInterpretacaoVsg]=useState("");
 const [avancados,setAvancados]=useState<AvancadosState>({}); const [erroCalculo,setErroCalculo]=useState(""); const [calculando,setCalculando]=useState(false); const [gerando,setGerando]=useState(false); const [erroGeracao,setErroGeracao]=useState(""); const [geradoId,setGeradoId]=useState<number|null>(null); const [metodo,setMetodo]=useState(usuario?.assinatura_metodo_preferido??"MANUAL"); const [aguardandoExterno,setAguardandoExterno]=useState(false); const [assinadoExternoAgora,setAssinadoExternoAgora]=useState(false); const [email,setEmail]=useState(""); const [enviando,setEnviando]=useState(false); const [resultadoEnvio,setResultadoEnvio]=useState<any>(null);
 useEffect(()=>{api.get<Provedor[]>("/assinatura/provedores").then(setProvedores).catch(()=>{})},[]);
 const aubPayload=()=>({...aub,idade_maior_igual_75:idade?Number(idade)>=75:aub.idade_maior_igual_75});
 const vsgPayload=()=>{const x=vsg.idade||idade;if(!x)throw new ApiError(422,"Informe a idade para o VSG-CRI.");return{...vsg,idade:Number(x)}};
 async function calcularEscores(){setCalculando(true);setErroCalculo("");try{if(usarRcri){const x=await api.post<any>("/calculators/rcri/run",rcri);setResultadoRcri(x.result);setInterpretacaoRcri(x.interpretation)}else setResultadoRcri(null);if(usarGupta){const ig=gupta.idade||idade;if(!ig)throw new ApiError(422,"Informe a idade para Gupta MICA.");const x=await api.post<any>("/calculators/gupta-mica/run",{...gupta,idade:Number(ig),asa:Number(gupta.asa)});setResultadoGupta(x.result);setInterpretacaoGupta(x.interpretation)}else setResultadoGupta(null);if(usarDasi){const x=await api.post<any>("/calculators/dasi/run",dasi);setResultadoDasi(x.result);setInterpretacaoDasi(x.interpretation)}else setResultadoDasi(null);if(usarAub){const x=await api.post<any>("/calculators/aub-has2/run",aubPayload());setResultadoAub(x.result);setInterpretacaoAub(x.interpretation)}else setResultadoAub(null);if(usarVsg){const x=await api.post<any>("/calculators/vsg-cri/run",vsgPayload());setResultadoVsg(x.result);setInterpretacaoVsg(x.interpretation)}else setResultadoVsg(null)}catch(e){setErroCalculo(e instanceof ApiError?e.message:"Não foi possível calcular.")}finally{setCalculando(false)}}
 const avancadoComResultado=Object.values(avancados).some(m=>m.selecionado&&m.result); const temResultado=Boolean(resultadoRcri||resultadoGupta||resultadoDasi||resultadoAub||resultadoVsg||avancadoComResultado); const podeGerar=procedimento.trim().length>0&&temResultado;
 async function gerarDocumento(){if(!podeGerar)return;setGerando(true);setErroGeracao("");try{const ig=gupta.idade||idade;const av=(slug:string)=>avancados[slug]?.selecionado&&avancados[slug]?.result?avancados[slug].payload:null;const x=await api.post<{id:number}>("/avaliacao-preoperatoria/gerar",{patient_name:patientName.trim()||null,idade:idade?Number(idade):null,procedimento_planejado:procedimento.trim(),indicacao_cirurgica:indicacao.trim()||null,capacidade_funcional:capacidadeFuncional.trim()||null,conduta_recomendada:conduta.trim()||null,endereco:endereco||null,rcri:usarRcri&&resultadoRcri?rcri:null,gupta:usarGupta&&resultadoGupta?{...gupta,idade:Number(ig),asa:Number(gupta.asa)}:null,dasi:usarDasi&&resultadoDasi?dasi:null,aub_has2:usarAub&&resultadoAub?aubPayload():null,vsg_cri:usarVsg&&resultadoVsg?vsgPayload():null,gscri:av("gscri"),sort:av("sort"),s_mpm:av("s-mpm")});setGeradoId(x.id)}catch(e){setErroGeracao(e instanceof ApiError?e.message:"Não foi possível gerar o documento.")}finally{setGerando(false)}}
 async function baixar(){if(!geradoId)return;try{const blob=await api.blob(`/document-templates/gerados/${geradoId}/pdf?metodo=${encodeURIComponent(metodo)}`);baixarBlob(blob,`avaliacao-preoperatoria-${geradoId}.pdf`);setAguardandoExterno(METODOS_MANUAL_EXTERNO.has(metodo))}catch(e){setErroGeracao(e instanceof ApiError?e.message:"Não foi possível baixar o PDF.")}}
 async function enviarPorEmail(){if(!geradoId||!email)return;setEnviando(true);try{const x=await api.post<any>(`/document-templates/gerados/${geradoId}/enviar-email`,{email});setResultadoEnvio(x)}finally{setEnviando(false)}}
 return <div style={{maxWidth:860}}><p className="eyebrow">Pacientes e prática</p><h1>Avaliação Cardiológica Pré-Operatória de Risco Cirúrgico</h1><p>Integra risco cardiovascular, capacidade funcional e mortalidade cirúrgica global sem misturar endpoints. <Link to={`/biblioteca?tema=${encodeURIComponent("Perioperatório")}`}>Árvores e referências na Biblioteca</Link>.</p>
 <div className="cartao"><label>Nome do paciente</label><input value={patientName} onChange={e=>setPatientName(e.target.value)}/><div className="grade grade--2"><div><label>Idade</label><input type="number" value={idade} onChange={e=>setIdade(e.target.value)}/></div><div><label>Capacidade funcional — descrição</label><input value={capacidadeFuncional} onChange={e=>setCapacidadeFuncional(e.target.value)}/></div></div><label>Procedimento</label><input value={procedimento} onChange={e=>setProcedimento(e.target.value)}/><label>Indicação</label><input value={indicacao} onChange={e=>setIndicacao(e.target.value)}/></div>
 <div className="cartao"><label><input type="checkbox" checked={usarRcri} onChange={e=>setUsarRcri(e.target.checked)}/> RCRI</label>{usarRcri&&Object.keys(RCRI_LABELS).map(k=><label key={k} style={{display:"flex",gap:8}}><input type="checkbox" checked={rcri[k as keyof RcriEntrada]} onChange={e=>setRcri({...rcri,[k]:e.target.checked})}/>{RCRI_LABELS[k as keyof RcriEntrada]}</label>)}</div>
 <div className="cartao"><label><input type="checkbox" checked={usarGupta} onChange={e=>setUsarGupta(e.target.checked)}/> Gupta MICA</label>{usarGupta&&<div className="grade grade--2"><input type="number" placeholder={idade} value={gupta.idade} onChange={e=>setGupta({...gupta,idade:e.target.value})}/><select value={gupta.status_funcional} onChange={e=>setGupta({...gupta,status_funcional:e.target.value})}><option value="independente">Independente</option><option value="parcialmente_dependente">Parcialmente dependente</option><option value="totalmente_dependente">Totalmente dependente</option></select><select value={gupta.asa} onChange={e=>setGupta({...gupta,asa:e.target.value})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select><select value={gupta.tipo_procedimento} onChange={e=>setGupta({...gupta,tipo_procedimento:e.target.value})}>{GUPTA_PROCEDIMENTOS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label><input type="checkbox" checked={gupta.creatinina_maior_1_5} onChange={e=>setGupta({...gupta,creatinina_maior_1_5:e.target.checked})}/> Creatinina &gt;1,5</label></div>}</div>
 <div className="cartao"><label><input type="checkbox" checked={usarDasi} onChange={e=>setUsarDasi(e.target.checked)}/> DASI</label>{usarDasi&&Object.keys(DASI_LABELS).map(k=><label key={k} style={{display:"flex",gap:8}}><input type="checkbox" checked={dasi[k as keyof DasiEntrada]} onChange={e=>setDasi({...dasi,[k]:e.target.checked})}/>{DASI_LABELS[k as keyof DasiEntrada]}</label>)}</div>
 <div className="cartao"><label><input type="checkbox" checked={usarAub} onChange={e=>setUsarAub(e.target.checked)}/> AUB-HAS2</label>{usarAub&&<>{Object.keys(AUB_LABELS).map(k=><label key={k} style={{display:"flex",gap:8}}><input type="checkbox" checked={aub[k as keyof AubEntrada] as boolean} onChange={e=>setAub({...aub,[k]:e.target.checked})}/>{AUB_LABELS[k as keyof typeof AUB_LABELS]}</label>)}</>}</div>
 <div className="cartao"><label><input type="checkbox" checked={usarVsg} onChange={e=>setUsarVsg(e.target.checked)}/> VSG-CRI</label>{usarVsg&&<><input type="number" value={vsg.idade} placeholder={idade} onChange={e=>setVsg({...vsg,idade:e.target.value})}/>{Object.keys(VSG_LABELS).map(k=><label key={k} style={{display:"flex",gap:8}}><input type="checkbox" checked={vsg[k as keyof VsgEntrada] as boolean} onChange={e=>setVsg({...vsg,[k]:e.target.checked})}/>{VSG_LABELS[k as keyof typeof VSG_LABELS]}</label>)}</>}</div>
 <p className="eyebrow">Métodos avançados / populações específicas</p><CalculadorasPreOperatoriasAvancadas idade={idade} onChange={setAvancados}/><div className="cartao"><strong>ACS-NSQIP oficial</strong><p>Modelo externo dinâmico; registrar versão/data/CPT. Não congelar coeficientes locais.</p></div>
 {erroCalculo&&<p role="alert">{erroCalculo}</p>}<button className="botao" onClick={calcularEscores} disabled={calculando}>{calculando?"Calculando…":"Calcular métodos básicos selecionados"}</button>
 {temResultado&&<div className="cartao"><h3>Resultado integrado</h3>{resultadoRcri&&<p><b>RCRI:</b> {resultadoRcri.pontos} — {interpretacaoRcri}</p>}{resultadoGupta&&<p><b>Gupta:</b> {resultadoGupta.risco_pct}% — {interpretacaoGupta}</p>}{resultadoDasi&&<p><b>DASI:</b> {resultadoDasi.score} — {interpretacaoDasi}</p>}{resultadoAub&&<p><b>AUB-HAS2:</b> {resultadoAub.score} — {interpretacaoAub}</p>}{resultadoVsg&&<p><b>VSG-CRI:</b> {resultadoVsg.score} — {interpretacaoVsg}</p>}{Object.entries(avancados).filter(([,m])=>m.selecionado&&m.result).map(([s,m])=><p key={s}><b>{s.toUpperCase()}:</b> {m.interpretation}</p>)}<p>Não somar/promediar métodos: endpoints diferentes.</p></div>}
 {temResultado&&<div className="cartao"><label>Conduta e recomendações</label><textarea rows={4} value={conduta} onChange={e=>setConduta(e.target.value)}/><label>Endereço</label><select value={endereco} onChange={e=>setEndereco(e.target.value as typeof endereco)}><option value="">Nenhum</option><option value="profissional">Profissional</option><option value="residencial">Residencial</option></select>{!geradoId?<button className="botao" onClick={gerarDocumento} disabled={gerando||!podeGerar}>{gerando?"Gerando…":"Gerar documento"}</button>:<><label>Método de assinatura</label><select value={metodo} onChange={e=>setMetodo(e.target.value)}>{(provedores??[]).map(p=><option key={p.codigo} value={p.codigo}>{p.nome}</option>)}</select><button className="botao" onClick={baixar}>Baixar PDF</button>{aguardandoExterno&&<AssinaturaExternaITI metodo={metodo} nomeProvedor={provedores?.find(p=>p.codigo===metodo)?.nome??metodo} enviarUrl={`/document-templates/gerados/${geradoId}/assinatura-externa`} onConcluido={()=>{setAguardandoExterno(false);setAssinadoExternoAgora(true)}}/>}{assinadoExternoAgora&&<p>Assinatura conferida.</p>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/><button className="botao" onClick={enviarPorEmail} disabled={enviando||!email}>Enviar por e-mail</button>{resultadoEnvio&&<p>{resultadoEnvio.enviado?"E-mail enviado.":"Envio automático indisponível."}</p>}</>}{erroGeracao&&<p role="alert">{erroGeracao}</p>}</div>}
 </div>;
}