"""favoritos, reset de senha, banco de exames

Revision ID: 48223127d2f0
Revises: 7ed21b8f3738
Create Date: 2026-07-24 18:16:55.583550
"""
from alembic import op
import sqlalchemy as sa


revision = '48223127d2f0'
down_revision = '7ed21b8f3738'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('document_chunks_embedding_idx', table_name='document_chunks', postgresql_using='hnsw')
    op.drop_index('documents_search_idx', table_name='documents', postgresql_using='gin')
    op.drop_index('documents_trgm_idx', table_name='documents', postgresql_using='gin')
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'aprovado'::character varying"))
    op.drop_constraint('users_cpf_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.create_unique_constraint('users_cpf_key', 'users', ['cpf'])
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'aprovado'::character varying"))
    op.create_index('documents_trgm_idx', 'documents', ['title'], unique=False, postgresql_using='gin')
    op.create_index('documents_search_idx', 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('document_chunks_embedding_idx', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
