"""linha de base - esquema em producao

Revision ID: 84eeeb026a98
Revises: 
Create Date: 2026-07-26 21:01:14.971000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision = '84eeeb026a98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=False),
    sa.Column('brand_names', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('drug_class', sa.String(length=120), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('presentations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('commercial_presentations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dosing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('renal_adjustment', sa.Text(), nullable=True),
    sa.Column('hepatic_adjustment', sa.Text(), nullable=True),
    sa.Column('contraindications', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('interactions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('monitoring', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('pregnancy', sa.Text(), nullable=True),
    sa.Column('lactation', sa.Text(), nullable=True),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_reference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('half_life_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('half_life_note', sa.Text(), nullable=True),
    sa.Column('sbp_reduction_mmhg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('dbp_reduction_mmhg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('bp_evidence_source', sa.Text(), nullable=True),
    sa.Column('references', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugs_drug_class'), 'drugs', ['drug_class'], unique=False)
    op.create_index(op.f('ix_drugs_generic_name'), 'drugs', ['generic_name'], unique=False)
    op.create_index(op.f('ix_drugs_slug'), 'drugs', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('profession', sa.String(length=80), nullable=True),
    sa.Column('council_name', sa.String(length=20), nullable=True),
    sa.Column('council_number', sa.String(length=30), nullable=True),
    sa.Column('council_state', sa.String(length=2), nullable=True),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('crm', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_owner_id'), 'document_templates', ['owner_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('theme', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('source_refs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('evidence_level', sa.String(length=40), nullable=True),
    sa.Column('source_tier', sa.String(length=12), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gaps', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_published'), 'documents', ['published'], unique=False)
    op.create_index(op.f('ix_documents_slug'), 'documents', ['slug'], unique=True)
    op.create_index(op.f('ix_documents_source_tier'), 'documents', ['source_tier'], unique=False)
    op.create_index(op.f('ix_documents_theme'), 'documents', ['theme'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('recommendation_class', sa.String(length=10), nullable=False),
    sa.Column('evidence_level', sa.String(length=5), nullable=False),
    sa.Column('society', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('guideline_title', sa.String(length=400), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(length=80), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('document_slug', sa.String(length=255), nullable=True),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_published'), 'evidence_records', ['published'], unique=False)
    op.create_index(op.f('ix_evidence_records_slug'), 'evidence_records', ['slug'], unique=True)
    op.create_index(op.f('ix_evidence_records_theme'), 'evidence_records', ['theme'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='uq_favorito_unico')
    )
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('modality', sa.String(length=40), nullable=False),
    sa.Column('theme', sa.String(length=80), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('teaching_points', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('license', sa.String(length=80), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_images_modality'), 'gallery_images', ['modality'], unique=False)
    op.create_index(op.f('ix_gallery_images_published'), 'gallery_images', ['published'], unique=False)
    op.create_index(op.f('ix_gallery_images_slug'), 'gallery_images', ['slug'], unique=True)
    op.create_index(op.f('ix_gallery_images_theme'), 'gallery_images', ['theme'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('what_it_measures', sa.Text(), nullable=False),
    sa.Column('reference_range', sa.Text(), nullable=True),
    sa.Column('indications', sa.Text(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=80), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('source_refs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tests_category'), 'lab_tests', ['category'], unique=False)
    op.create_index(op.f('ix_lab_tests_published'), 'lab_tests', ['published'], unique=False)
    op.create_index(op.f('ix_lab_tests_slug'), 'lab_tests', ['slug'], unique=True)
    op.create_index(op.f('ix_lab_tests_theme'), 'lab_tests', ['theme'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_number', sa.String(length=60), nullable=False),
    sa.Column('initials', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('bed', sa.String(length=40), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('anamnesis', sa.Text(), nullable=True),
    sa.Column('physical_exam', sa.Text(), nullable=True),
    sa.Column('cardiac_exam', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vital_signs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imaging', sa.Text(), nullable=True),
    sa.Column('diagnostic_hypothesis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('labs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('pending', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_created_by'), 'patients', ['created_by'], unique=False)
    op.create_index(op.f('ix_patients_record_number'), 'patients', ['record_number'], unique=False)
    op.create_table('scientific_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('study_type', sa.String(length=60), nullable=False),
    sa.Column('authors', sa.String(length=300), nullable=True),
    sa.Column('journal', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=120), nullable=True),
    sa.Column('pmid', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_findings', sa.Text(), nullable=False),
    sa.Column('clinical_implications', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=80), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scientific_studies_published'), 'scientific_studies', ['published'], unique=False)
    op.create_index(op.f('ix_scientific_studies_slug'), 'scientific_studies', ['slug'], unique=True)
    op.create_index(op.f('ix_scientific_studies_theme'), 'scientific_studies', ['theme'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('fontes', sa.Text(), nullable=True),
    sa.Column('fontes_pubmed', sa.Text(), nullable=True),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_saida', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_created_at'), 'ai_messages', ['created_at'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_name_temp', sa.String(length=200), nullable=True),
    sa.Column('patient_phone_temp', sa.String(length=30), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('appointment_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_owner_id'), 'appointments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('titulo_secao', sa.String(length=300), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('tokens_aprox', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('document_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('rendered_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_created_by'), 'generated_documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_generated_documents_patient_id'), 'generated_documents', ['patient_id'], unique=False)
    op.create_table('patient_ai_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('case_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('differential_diagnosis', sa.Text(), nullable=False),
    sa.Column('suggested_workup', sa.Text(), nullable=False),
    sa.Column('treatment_considerations', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources_pubmed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_created_by'), 'prescriptions', ['created_by'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_created_by'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_table('patient_problems')
    op.drop_table('patient_notes')
    op.drop_table('patient_ai_suggestions')
    op.drop_index(op.f('ix_generated_documents_patient_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_created_by'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_table('document_revisions')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_owner_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_ai_messages_created_at'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_scientific_studies_theme'), table_name='scientific_studies')
    op.drop_index(op.f('ix_scientific_studies_slug'), table_name='scientific_studies')
    op.drop_index(op.f('ix_scientific_studies_published'), table_name='scientific_studies')
    op.drop_table('scientific_studies')
    op.drop_index(op.f('ix_patients_record_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_by'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_lab_tests_theme'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_slug'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_published'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_category'), table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index(op.f('ix_gallery_images_theme'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_slug'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_published'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_modality'), table_name='gallery_images')
    op.drop_table('gallery_images')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_evidence_records_theme'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_slug'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_published'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_documents_theme'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_tier'), table_name='documents')
    op.drop_index(op.f('ix_documents_slug'), table_name='documents')
    op.drop_index(op.f('ix_documents_published'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_templates_owner_id'), table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_drugs_slug'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_generic_name'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_drug_class'), table_name='drugs')
    op.drop_table('drugs')
    # ### end Alembic commands ###
