"""CorVIA Heart Team Virtual.

Revision ID: f87h20260831
Revises: f86d20260829
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "f87h20260831"
down_revision = "f86d20260829"
branch_labels = None
depends_on = None

J = postgresql.JSONB


def upgrade() -> None:
    op.create_table("heart_team_cases",
        sa.Column("id", sa.Integer, primary_key=True), sa.Column("owner_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("created_by_id", sa.Integer, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("status", sa.String(32), nullable=False), sa.Column("question", sa.Text), sa.Column("analysis_scope", sa.String(24), nullable=False), sa.Column("selected_agents", J, nullable=False), sa.Column("input_data", J, nullable=False), sa.Column("structured_case", J, nullable=False), sa.Column("missing_data", J, nullable=False), sa.Column("risk_classification", J, nullable=False), sa.Column("result", J, nullable=False),
        sa.Column("input_hash", sa.String(64)), sa.Column("pipeline_version", sa.String(40), nullable=False), sa.Column("model_versions", J, nullable=False), sa.Column("tokens_input", sa.Integer, nullable=False), sa.Column("tokens_output", sa.Integer, nullable=False), sa.Column("estimated_cost_micros", sa.BigInteger, nullable=False), sa.Column("reserved_cost_micros", sa.BigInteger, nullable=False),
        sa.Column("deidentified_confirmed_at", sa.DateTime(timezone=True)), sa.Column("medical_review_confirmed_at", sa.DateTime(timezone=True)), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('draft','queued','analyzing','awaiting_review','completed','rejected','failed','unusable')", name="ck_heart_team_cases_status"), sa.CheckConstraint("estimated_cost_micros >= 0 AND reserved_cost_micros >= 0", name="ck_heart_team_case_cost"))
    op.create_index("ix_heart_team_cases_owner_id", "heart_team_cases", ["owner_id"]); op.create_index("ix_heart_team_cases_status", "heart_team_cases", ["status"]); op.create_index("ix_heart_team_cases_input_hash", "heart_team_cases", ["input_hash"])
    op.create_table("heart_team_attachments",
        sa.Column("id", sa.Integer, primary_key=True), sa.Column("case_id", sa.Integer, sa.ForeignKey("heart_team_cases.id", ondelete="CASCADE"), nullable=False), sa.Column("owner_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("kind", sa.String(32), nullable=False), sa.Column("reference_id", sa.String(160)), sa.Column("storage_key", sa.String(120), unique=True), sa.Column("original_name_encrypted", sa.LargeBinary), sa.Column("media_type", sa.String(120), nullable=False), sa.Column("size_bytes", sa.Integer, nullable=False), sa.Column("source_sha256", sa.String(64)), sa.Column("sha256", sa.String(64), nullable=False), sa.Column("sanitization_report", J, nullable=False), sa.Column("objective_extract", J, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("size_bytes >= 0", name="ck_heart_team_attachment_size"))
    for col in ("case_id", "owner_id", "sha256"): op.create_index(f"ix_heart_team_attachments_{col}", "heart_team_attachments", [col])
    op.create_table("heart_team_analysis_jobs", sa.Column("id", sa.Integer, primary_key=True), sa.Column("case_id", sa.Integer, sa.ForeignKey("heart_team_cases.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("owner_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("actor_id", sa.Integer, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("attempts", sa.Integer, nullable=False), sa.Column("last_error_code", sa.String(80)), sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("status IN ('queued','running','completed','failed')", name="ck_heart_team_analysis_job_status"))
    for col in ("owner_id", "status", "next_attempt_at"): op.create_index(f"ix_heart_team_analysis_jobs_{col}", "heart_team_analysis_jobs", [col])
    op.create_table("heart_team_opinions",
        sa.Column("id", sa.Integer, primary_key=True), sa.Column("case_id", sa.Integer, sa.ForeignKey("heart_team_cases.id", ondelete="CASCADE"), nullable=False), sa.Column("agent_key", sa.String(64), nullable=False), sa.Column("round_name", sa.String(24), nullable=False), sa.Column("position", J, nullable=False), sa.Column("content", J, nullable=False), sa.Column("source_ids", J, nullable=False), sa.Column("confidence", sa.String(24), nullable=False), sa.Column("content_hash", sa.String(64), nullable=False), sa.Column("model_name", sa.String(120), nullable=False), sa.Column("tokens_input", sa.Integer, nullable=False), sa.Column("tokens_output", sa.Integer, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("case_id", "agent_key", "round_name", name="uq_heart_team_opinion_round"))
    op.create_index("ix_heart_team_opinions_case_id", "heart_team_opinions", ["case_id"]); op.create_index("ix_heart_team_opinions_agent_key", "heart_team_opinions", ["agent_key"])
    op.create_table("heart_team_suggestions", sa.Column("id", sa.Integer, primary_key=True), sa.Column("case_id", sa.Integer, sa.ForeignKey("heart_team_cases.id", ondelete="CASCADE"), nullable=False), sa.Column("category", sa.String(48), nullable=False), sa.Column("original_text", sa.Text, nullable=False), sa.Column("original_hash", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_heart_team_suggestions_case_id", "heart_team_suggestions", ["case_id"])
    op.create_table("heart_team_suggestion_reviews", sa.Column("id", sa.Integer, primary_key=True), sa.Column("suggestion_id", sa.Integer, sa.ForeignKey("heart_team_suggestions.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("reviewer_id", sa.Integer, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("decision", sa.String(16), nullable=False), sa.Column("final_text", sa.Text), sa.Column("original_hash", sa.String(64), nullable=False), sa.Column("final_hash", sa.String(64), nullable=False), sa.Column("note", sa.Text), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("decision IN ('accepted','rejected','edited')", name="ck_heart_team_suggestion_review"))
    op.create_table("heart_team_final_reviews", sa.Column("id", sa.Integer, primary_key=True), sa.Column("case_id", sa.Integer, sa.ForeignKey("heart_team_cases.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("reviewer_id", sa.Integer, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("decision", sa.String(16), nullable=False), sa.Column("medical_responsibility_confirmed", sa.Boolean, nullable=False), sa.Column("human_decisions_confirmed", sa.Boolean, nullable=False), sa.Column("original_snapshot", J, nullable=False), sa.Column("final_snapshot", J, nullable=False), sa.Column("original_hash", sa.String(64), nullable=False), sa.Column("final_hash", sa.String(64), nullable=False), sa.Column("note", sa.Text), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("decision IN ('accepted','rejected')", name="ck_heart_team_final_review"))
    op.create_table("heart_team_patient_records", sa.Column("id", sa.Integer, primary_key=True), sa.Column("case_id", sa.Integer, sa.ForeignKey("heart_team_cases.id", ondelete="RESTRICT"), nullable=False, unique=True), sa.Column("owner_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("patient_profile_id", sa.Integer, sa.ForeignKey("patient_profiles.id", ondelete="RESTRICT"), nullable=False), sa.Column("reviewer_id", sa.Integer, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("decision", sa.String(16), nullable=False), sa.Column("final_hash", sa.String(64), nullable=False), sa.Column("provenance", J, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("decision IN ('accepted','rejected')", name="ck_heart_team_patient_record_decision"))
    op.create_index("ix_heart_team_patient_records_owner_id", "heart_team_patient_records", ["owner_id"]); op.create_index("ix_heart_team_patient_records_patient_profile_id", "heart_team_patient_records", ["patient_profile_id"]); op.create_index("ix_heart_team_patient_records_reviewer_id", "heart_team_patient_records", ["reviewer_id"])
    op.create_table("heart_team_audit_events", sa.Column("id", sa.Integer, primary_key=True), sa.Column("case_id", sa.Integer, sa.ForeignKey("heart_team_cases.id", ondelete="CASCADE"), nullable=False), sa.Column("actor_id", sa.Integer, sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("action", sa.String(80), nullable=False), sa.Column("detail", J, nullable=False), sa.Column("previous_hash", sa.String(64), nullable=False), sa.Column("event_hash", sa.String(64), nullable=False, unique=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_heart_team_audit_events_case_id", "heart_team_audit_events", ["case_id"]); op.create_index("ix_heart_team_audit_events_action", "heart_team_audit_events", ["action"])
    op.create_table("heart_team_cache", sa.Column("id", sa.Integer, primary_key=True), sa.Column("owner_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("cache_key", sa.String(64), nullable=False, unique=True), sa.Column("encrypted_payload", sa.LargeBinary, nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_heart_team_cache_owner_id", "heart_team_cache", ["owner_id"]); op.create_index("ix_heart_team_cache_expires_at", "heart_team_cache", ["expires_at"])
    op.create_table("heart_team_cost_ledger", sa.Column("id", sa.Integer, primary_key=True), sa.Column("case_id", sa.Integer, sa.ForeignKey("heart_team_cases.id", ondelete="CASCADE"), nullable=False), sa.Column("owner_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("agent_key", sa.String(64), nullable=False), sa.Column("phase", sa.String(24), nullable=False), sa.Column("reserved_micros", sa.BigInteger, nullable=False), sa.Column("actual_micros", sa.BigInteger, nullable=False), sa.Column("tokens_input", sa.Integer, nullable=False), sa.Column("tokens_output", sa.Integer, nullable=False), sa.Column("model_name", sa.String(120), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_heart_team_cost_ledger_case_id", "heart_team_cost_ledger", ["case_id"]); op.create_index("ix_heart_team_cost_ledger_owner_id", "heart_team_cost_ledger", ["owner_id"])
    op.execute("""
      CREATE FUNCTION heart_team_reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN RAISE EXCEPTION 'immutable Heart Team record'; END; $$;
    """)
    for table in ("heart_team_opinions", "heart_team_suggestions", "heart_team_suggestion_reviews", "heart_team_final_reviews", "heart_team_patient_records", "heart_team_audit_events", "heart_team_cost_ledger"):
        op.execute(f"CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION heart_team_reject_mutation()")


def downgrade() -> None:
    for table in ("heart_team_opinions", "heart_team_suggestions", "heart_team_suggestion_reviews", "heart_team_final_reviews", "heart_team_patient_records", "heart_team_audit_events", "heart_team_cost_ledger"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_immutable ON {table}")
    op.execute("DROP FUNCTION IF EXISTS heart_team_reject_mutation()")
    for table in ("heart_team_cost_ledger", "heart_team_cache", "heart_team_audit_events", "heart_team_patient_records", "heart_team_final_reviews", "heart_team_suggestion_reviews", "heart_team_suggestions", "heart_team_opinions", "heart_team_analysis_jobs", "heart_team_attachments", "heart_team_cases"):
        op.drop_table(table)
