"""WhatsApp Assistant
Revision ID: f88w20260831
Revises: f87h20260831
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="f88w20260831";down_revision="f87h20260831";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("whatsapp_links",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("phone_hash",sa.String(64),nullable=False,unique=True),sa.Column("phone_cipher",sa.LargeBinary,nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("permissions",postgresql.JSONB,nullable=False),sa.Column("retention_days",sa.Integer,nullable=False),sa.Column("consent_purpose",sa.String(240),nullable=False),sa.Column("consent_at",sa.DateTime(timezone=True),nullable=False),sa.Column("paired_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revoked_at",sa.DateTime(timezone=True)),sa.Column("pin_hash",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("whatsapp_pairings",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("code_hash",sa.String(64),nullable=False,unique=True),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("used_at",sa.DateTime(timezone=True)),sa.Column("revoked_at",sa.DateTime(timezone=True)),sa.Column("attempts",sa.Integer,nullable=False),sa.Column("retention_days",sa.Integer,nullable=False),sa.Column("permissions",postgresql.JSONB,nullable=False),sa.Column("pin_hash",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("whatsapp_webhook_events",sa.Column("id",sa.Integer,primary_key=True),sa.Column("provider_event_id",sa.String(180),unique=True,nullable=False),sa.Column("payload_hash",sa.String(64),nullable=False),sa.Column("link_id",sa.Integer,sa.ForeignKey("whatsapp_links.id",ondelete="SET NULL")),sa.Column("provider_created_at",sa.DateTime(timezone=True)),sa.Column("status",sa.String(30),nullable=False),sa.Column("failure_code",sa.String(80)),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False),sa.Column("processed_at",sa.DateTime(timezone=True)))
 op.create_table("whatsapp_messages",sa.Column("id",sa.Integer,primary_key=True),sa.Column("link_id",sa.Integer,sa.ForeignKey("whatsapp_links.id",ondelete="CASCADE"),nullable=False),sa.Column("owner_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("provider_message_id",sa.String(180),unique=True),sa.Column("direction",sa.String(10),nullable=False),sa.Column("message_type",sa.String(20),nullable=False),sa.Column("payload_cipher",sa.LargeBinary,nullable=False),sa.Column("pii_kinds",postgresql.JSONB,nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("authorization_level",sa.Integer,nullable=False),sa.Column("meta_billable",sa.Boolean,nullable=False),sa.Column("estimated_cost_microunits",sa.Integer,nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("whatsapp_commands",sa.Column("id",sa.Integer,primary_key=True),sa.Column("link_id",sa.Integer,sa.ForeignKey("whatsapp_links.id",ondelete="CASCADE"),nullable=False),sa.Column("owner_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("message_id",sa.Integer,sa.ForeignKey("whatsapp_messages.id",ondelete="SET NULL")),sa.Column("kind",sa.String(60),nullable=False),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("level",sa.Integer,nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("payload_cipher",sa.LargeBinary,nullable=False),sa.Column("confirmation_token_hash",sa.String(64)),sa.Column("confirmation_expires_at",sa.DateTime(timezone=True)),sa.Column("undo_token_hash",sa.String(64)),sa.Column("undo_expires_at",sa.DateTime(timezone=True)),sa.Column("requires_in_app",sa.Boolean,nullable=False),sa.Column("result_cipher",sa.LargeBinary),sa.Column("executed_at",sa.DateTime(timezone=True)),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("owner_id","idempotency_key",name="uq_whatsapp_command_owner_key"))
 op.create_table("whatsapp_usage_metrics",sa.Column("id",sa.Integer,primary_key=True),sa.Column("owner_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("link_id",sa.Integer,sa.ForeignKey("whatsapp_links.id",ondelete="SET NULL")),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("operation",sa.String(80),nullable=False),sa.Column("provider",sa.String(30),nullable=False),sa.Column("model",sa.String(100)),sa.Column("input_units",sa.Integer,nullable=False),sa.Column("output_units",sa.Integer,nullable=False),sa.Column("estimated_cost_microunits",sa.Integer,nullable=False),sa.Column("latency_ms",sa.Integer,nullable=False),sa.Column("success",sa.Boolean,nullable=False),sa.Column("blocked_reason",sa.String(120)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("owner_id","idempotency_key",name="uq_whatsapp_metric_owner_key"))
 op.create_table("whatsapp_heart_team_jobs",sa.Column("id",sa.Integer,primary_key=True),sa.Column("command_id",sa.Integer,sa.ForeignKey("whatsapp_commands.id",ondelete="RESTRICT"),nullable=False,unique=True),sa.Column("case_id",sa.Integer,sa.ForeignKey("heart_team_cases.id",ondelete="RESTRICT"),nullable=False,unique=True),sa.Column("owner_id",sa.Integer,sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("link_id",sa.Integer,sa.ForeignKey("whatsapp_links.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("attempts",sa.Integer,nullable=False),sa.Column("next_attempt_at",sa.DateTime(timezone=True),nullable=False),sa.Column("provider_message_id",sa.String(180)),sa.Column("last_error_code",sa.String(80)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)))
 op.create_table("whatsapp_outbound_outbox",sa.Column("id",sa.Integer,primary_key=True),sa.Column("idempotency_key",sa.String(180),nullable=False,unique=True),sa.Column("owner_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("link_id",sa.Integer,sa.ForeignKey("whatsapp_links.id",ondelete="CASCADE"),nullable=False),sa.Column("job_id",sa.Integer,sa.ForeignKey("whatsapp_heart_team_jobs.id",ondelete="CASCADE")),sa.Column("mode",sa.String(20),nullable=False),sa.Column("payload_cipher",sa.LargeBinary,nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("attempts",sa.Integer,nullable=False),sa.Column("estimated_cost_microunits",sa.Integer,nullable=False),sa.Column("provider_message_id",sa.String(180)),sa.Column("last_error_code",sa.String(80)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("sent_at",sa.DateTime(timezone=True)),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("whatsapp_opt_events",sa.Column("id",sa.Integer,primary_key=True),sa.Column("link_id",sa.Integer,sa.ForeignKey("whatsapp_links.id",ondelete="SET NULL")),sa.Column("owner_id",sa.Integer,sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("event",sa.String(20),nullable=False),sa.Column("purpose",sa.String(240),nullable=False),sa.Column("detail",sa.Text),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("whatsapp_drafts",sa.Column("id",sa.Integer,primary_key=True),sa.Column("owner_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("link_id",sa.Integer,sa.ForeignKey("whatsapp_links.id",ondelete="CASCADE"),nullable=False),sa.Column("kind",sa.String(20),nullable=False),sa.Column("title_cipher",sa.LargeBinary),sa.Column("body_cipher",sa.LargeBinary,nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("whatsapp_summary_cache",sa.Column("id",sa.Integer,primary_key=True),sa.Column("owner_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("cache_key",sa.String(64),nullable=False),sa.Column("media_sha256",sa.String(64),nullable=False),sa.Column("model",sa.String(100),nullable=False),sa.Column("pipeline_version",sa.String(40),nullable=False),sa.Column("result_cipher",sa.LargeBinary,nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("last_accessed_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("owner_id","cache_key",name="uq_whatsapp_summary_cache_owner_key"))
def downgrade():
 for t in ("whatsapp_summary_cache","whatsapp_drafts","whatsapp_opt_events","whatsapp_outbound_outbox","whatsapp_heart_team_jobs","whatsapp_usage_metrics","whatsapp_commands","whatsapp_messages","whatsapp_webhook_events","whatsapp_pairings","whatsapp_links"):op.drop_table(t)
